### ISSUE TITLE
Lista de markdowns para o repositório do usuário

### ISSUE THREAD

**Issue by leopoldomt** [JoaoPauloLins/IF1001-GithubResearcher#2]

**Comment by JoaoPauloLins** [comment]
![viewmodelghr](https://user-images.githubusercontent.com/20371104/42640539-e6ef9bb4-85c8-11e8-8222-76a5a53629e8.PNG)
![dighr](https://user-images.githubusercontent.com/20371104/42640672-315df89e-85c9-11e8-86ec-f429344cf262.PNG)
